### ISSUE TITLE
Environment files with different formats

### ISSUE THREAD

**Issue by ndench** [weareinteractive/ansible-environment#9]
Some files require environment variables to be specified in different formats, some that I'm aware of:

For system wide configuration (already supported):
```
# /etc/environment
name=value
```

For php-fpm:
```
# /etc/php/7.1/fpm/pool.d/www.conf
env[name] = "value"
```

For specific users with either bash or zsh shells:
```
# ~/.bashrc or ~/.zshrc
export name=value
```

For specific users with the fish shell:
```
# ~/.config/fish/config.fish
set -x name=value
```

I'm stuck on the php-fpm configuration at the moment which has forced me to write my own role. I would rather contribute to this one though. I'm not entirely sure how to go about it, I don't think it'll work to allow the format of the file to be specified as regex or anything. The best way would be to support a number of formats, and each environment file is allowed to specify which format it requires.

Would you be open to a pull request?

**Comment by franklinkim** [comment]
This role actually was only supposed to take care of the `/etc/environment` file and any thing that might be related with it. I admit, it turned out not to do a lot and could be used to configure other files as well.

In my opinion though, configuring files like `.zshrc` should be part of a ZSH role.
